import pandas as pd
import os

def generate_features(ticker="AAPL"):
    """
    Loads cleaned data, adds technical indicators, and saves the final dataset.
    
    Parameters:
        ticker (str): The stock or ETF symbol (default: "AAPL").
    """
    
    # define paths
    input_path = f"data/processed/{ticker}_cleaned.csv"
    output_dir = "data/processed"
    output_path = f"{output_dir}/{ticker}_final.csv"
    
    print(f"Generating features for {ticker}...")
    
    # load cleaned data
    try:
        df = pd.read_csv(input_path, index_col='date', parse_dates=True)
    except FileNotFoundError:
        print(f"Error: File not found at {input_path}")
        return

    # 1. Daily Returns (percentage change)
    df['daily_return'] = df['close'].pct_change()

    # 2. 20-day Moving Average
    df['ma_20'] = df['close'].rolling(window=20).mean()

    # 3. 50-day Moving Average
    df['ma_50'] = df['close'].rolling(window=50).mean()

    # drop rows with NaN values generated by rolling windows and pct_change
    df.dropna(inplace=True)
    
    # save to csv
    df.to_csv(output_path)
    print(f"Feature-engineered data saved to {output_path}")

if __name__ == "__main__":
    generate_features()
