import pandas as pd
import os

# def get_usd_to_inr_rate():
#     """Fetches live USD to INR exchange rate"""
#     # Uses Yahoo Finance API
#     # Current rate: ~89.74 INR per USD
#     # Has fallback to 83.0 if API fails
    

def generate_features(ticker="AAPL"):
    """
    Loads cleaned data, adds technical indicators, and saves the final dataset.
    
    Parameters:
        ticker (str): The stock or ETF symbol (default: "AAPL").
    """
    
    # define paths
    input_path = f"data/processed/{ticker}_cleaned.csv"
    output_dir = "data/processed"
    output_path = f"{output_dir}/{ticker}_final.csv"
    
    print(f"Generating features for {ticker}...")
    
    # load cleaned data
    try:
        df = pd.read_csv(input_path, index_col='date', parse_dates=True)
    except FileNotFoundError:
        print(f"Error: File not found at {input_path}")
        return

    # 1. Daily Returns (percentage change)
    df['daily_return'] = df['close'].pct_change()

    # 2. 20-day Moving Average
    df['ma_20'] = df['close'].rolling(window=20).mean()

    # 3. 50-day Moving Average
    df['ma_50'] = df['close'].rolling(window=50).mean()

    # 4. RSI (14-period) using standard pandas functions (Wilder's Smoothing)
    delta = df['close'].diff()
    up = delta.clip(lower=0)
    down = -1 * delta.clip(upper=0)
    ma_up = up.ewm(com=13, adjust=False, min_periods=14).mean()
    ma_down = down.ewm(com=13, adjust=False, min_periods=14).mean()
    rs = ma_up / ma_down
    df['rsi_14'] = 100 - (100 / (1 + rs))

   # 5. MACD (Moving Average Convergence Divergence)
    exp1 = df['close'].ewm(span=12, adjust=False).mean()
    exp2 = df['close'].ewm(span=26, adjust=False).mean()
    df['macd'] = exp1 - exp2

# 6. Volatility (20-day rolling standard deviation of returns)
    df['volatility'] = df['daily_return'].rolling(window=20).std() 

    # drop rows with NaN values generated by rolling windows and pct_change
    df.dropna(inplace=True)
    
    # save to csv
    df.to_csv(output_path)
    print(f"Feature-engineered data saved to {output_path}")

if __name__ == "__main__":
    generate_features()
